### ISSUE TITLE
Real build infrastructure powered by CMake

### ISSUE THREAD

**Issue by TheAssassin** [probonopd/gs-plugin-appimage#3]
I'm working on a CMake based build infrastructure. The BUILDING file is mainly aiming to install all the software system-wide, which is not preferrable.

**Comment by probonopd** [comment]
Check out https://github.com/GNOME/gnome-software, they are using `meson`...

**Comment by probonopd** [comment]
Eventually we may want this to be merged upstream; so I am not sure whether it's now a good investment of time to do CMake.

**Comment by TheAssassin** [comment]
Our tools use CMake. So it's worth using it. I don't really care what GNOME think they have to use upstream, they often use brand new, untested and unavailable dependencies. I am including their stuff by building it with meson and then importing it into CMake.

**Comment by probonopd** [comment]
Not trying to stop you...

**Comment by TheAssassin** [comment]
Building gnome-software is highly annoying. Even on the latest Ubuntu, it complains about some polkit files which are apparently outdated. GNOME software is annoying...

**Comment by probonopd** [comment]
Actually we don't need to build gnome-software. (I thought so too, initially -- but we don't.) We just need to build this one plugin!

```
gcc -shared -o libgs_plugin_appimage.so gs-plugin-appimage.c -fPIC `pkg-config --libs --cflags gnome-software` -lappimage -DI_KNOW_THE_GNOME_SOFTWARE_API_IS_SUBJECT_TO_CHANGE
```

Works for me...

When I then copy the resulting file to the system location, then the system GS will use it.

**Comment by TheAssassin** [comment]
... that links to GNOME Software. And if you want to build it on <18.04 you need a newer version. And even if you build it on 18.04, linking is a bit awkward.

**Comment by probonopd** [comment]
You are right of course. At this moment I only care about 18.04+ for this project.

**Comment by probonopd** [comment]
https://travis-ci.com/probonopd/gs-plugin-appimage/jobs/126970633#L2466

Is it possible to just build `libappimage` but not AppImageKit `runtime` without needing xxd, desktop-file-validate and such things?

**Comment by TheAssassin** [comment]
Actually, AppImageKit is included with CMake's `EXCLUDE_FROM_ALL` flag. Maybe some target accidentally depends on the runtime target. 

But that's a separate issue. This feature has been implemented.

**Comment by TheAssassin** [comment]
@probonopd that's simply a build environment check. These are _always_ done before the build, i.e., in the CMake phase. And it's of course necessary to check for _all_ build dependencies, whatever you intend to build. If you don't want to install these two extra packages, we'd need to introduce another CMake variable.

**Comment by probonopd** [comment]
Can't we have something like `make libappimage` that would only pull in those dependencies that are actually needed?

**Comment by TheAssassin** [comment]
... what? Platform checks are run during the configure phase, not during the make phase.

**Comment by probonopd** [comment]
Hence I like building everyhting using build.sh ;-)

**Comment by probonopd** [comment]
Opened a feature request at https://github.com/AppImage/AppImageKit/issues/798; continuing there.
