### ISSUE TITLE
Build on Travis CI fails: gnome-software.h: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [probonopd/gs-plugin-appimage#6]
Let's build on Travis CI. Since Ubuntu 14.04 comes with a "too old" GNOME Software (I guess), let's use Docker following [these](https://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/) instructions.

**Comment by probonopd** [comment]
Once we have the plug-in working as it should, we could think about compiling modern GNOME Software for Ubuntu 14.04 and shipping it, along with the plug-in, as an AppImage. But this is second priority.

**Comment by probonopd** [comment]
Even if the compilation inside Docker fails, Travis CI build exits with 0. Do you know how to change that @TheAssassin?

Example:
https://travis-ci.org/probonopd/gs-plugin-appimage/jobs/386130742#L2833

**Comment by probonopd** [comment]
https://travis-ci.org/probonopd/gs-plugin-appimage/jobs/386141291#L2830-L2833

```
gs-plugin-appimage.c:5:10: fatal error: gnome-software.h: No such file or directory
 #include <gnome-software.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

Why the heck?! The stuff seems to be there...

https://travis-ci.org/probonopd/gs-plugin-appimage/jobs/386141291#L2418

```
/usr/include/gnome-software/gs-permission.h
/usr/include/gnome-software/gs-os-release.h
/usr/include/gnome-software/gs-category.h
/usr/include/gnome-software/gs-utils.h
/usr/include/gnome-software/gs-channel.h
/usr/include/gnome-software/gs-plugin-vfuncs.h
/usr/include/gnome-software/gnome-software.h
/usr/include/gnome-software/gs-plugin-types.h
/usr/include/gnome-software/gs-permission-value.h
/usr/include/gnome-software/gs-app-list.h
/usr/include/gnome-software/gs-auth.h
/usr/include/gnome-software/gs-plugin.h
/usr/include/gnome-software/gs-app.h
/usr/include/gnome-software/gs-price.h
/usr/include/gnome-software/gs-plugin-event.h
-pthread -I/usr/include/gnome-software -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libappstream-glib -I/usr/include/uuid -I/usr/include/libgcab-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lcairo-gobject -lcairo -lappstream-glib -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

**Comment by TheAssassin** [comment]
@probonopd maybe the syntax is `#include <gnome-software.h>`? How do other plugins include the files?

**Comment by probonopd** [comment]
https://github.com/GNOME/gnome-software/blob/7cf391ca7ac6ce006f35f6e0dbfe32fe56155f4e/contrib/gs-plugin-example.c#L22

```
#include <gnome-software.h>
```

**Comment by TheAssassin** [comment]
The CMake build system uses pkg-config and lets CMake internals worry about including and linking. Works great in a bionic container.

**Comment by probonopd** [comment]
It's black magic to me but hey, it's working black magic ;-)
